require('dotenv').config();

const express = require('express');
const Anthropic = require('@anthropic-ai/sdk');
const axios = require('axios');

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

let anthropic = null;
function getAnthropicClient() {
  if (!anthropic) {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY environment variable is not set');
    }
    anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return anthropic;
}

// ── Health check ─────────────────────────────────────────────────────────────

app.get('/health', (req, res) => {
  res.send('server is running');
});

// ── Webhook endpoint ──────────────────────────────────────────────────────────

app.post('/webhook', async (req, res) => {
  try {
    const payload = req.body;

    // Extract contact fields from GHL webhook payload
    const firstName   = payload.first_name   || payload.firstName   || 'there';
    const companyName = payload.company_name  || payload.companyName || payload.company || '';
    const email       = payload.email         || payload.contactEmail || '';
    const tagsArray   = Array.isArray(payload.tags) ? payload.tags : (payload.tags ? String(payload.tags).split(',').map(t => t.trim()) : []);
    const contactId   = payload.contact_id    || payload.contactId   || payload.id || '';

    // Detect profession from tags, industry, or title fields
    const allText = [payload.industry, payload.title, payload.type, ...tagsArray].join(' ').toLowerCase();
    const profession = /mortgage|lender|loan/.test(allText) ? 'mortgage lender' : 'realtor';

    if (!email) {
      console.warn('Webhook received with no email address — skipping.');
      return res.status(400).json({ error: 'Missing email address in payload' });
    }

    console.log(`Processing contact: ${firstName} <${email}> — ${companyName} (${profession})`);

    // ── Generate email with Claude ──────────────────────────────────────────

    const emailBody = await generateEmail({ firstName, companyName, profession });
    console.log('Email generated by Claude:\n', emailBody);

    // ── Send email via GHL API ──────────────────────────────────────────────

    await sendEmailViaGHL({ contactId, email, firstName, emailBody });
    console.log(`Email sent to ${email}`);

    res.json({ success: true, message: `Email sent to ${email}` });

  } catch (err) {
    console.error('Error processing webhook:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── Claude email generator ────────────────────────────────────────────────────

async function generateEmail({ firstName, companyName, profession }) {
  const isLender = profession === 'mortgage lender';

  const message = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 300,
    system: `You are Dane Saunders, founder of DaneOmedia in Ventura, CA. DaneOmedia creates professional photos, video, and social media content built specifically for realtors and mortgage lenders — helping them look more credible online, attract more clients, and make a lasting impression. You are reaching out to a ${profession} for the first time. You write like a real person: casual, confident, and direct. Short punchy sentences. No fluff.

STRICT RULES YOU MUST FOLLOW:
- Write exactly 4 short sentences. No more, no less.
- Never use dashes or hyphens anywhere.
- Never use bullet points or lists.
- Never use these words: cold, outbound, pipeline, deliverability, leverage, solutions, agency, strategy, tighten, deliver, campaigns, marketing, outreach.
- Do not include a greeting, subject line, sign off, or your name.
- Just write the 4 sentences and nothing else.`,
    messages: [
      {
        role: 'user',
        content: `Write 4 sentences to ${firstName}${companyName ? ` at ${companyName}` : ''}, a ${profession}.

Sentence 1: Greet ${firstName} warmly and casually mention you work with ${isLender ? 'mortgage lenders' : 'realtors'} in the area on photos, video, and content.
Sentence 2: Say that ${isLender ? 'lenders who have strong personal brand content build more trust with borrowers and get more referrals' : 'realtors who have strong photos, video, and content win more listings because sellers choose the agent who looks the most professional and put-together'}.
Sentence 3: Make it punchy and specific — ${isLender ? 'most lenders blend into the background online and great content is what sets the ones who grow apart from the ones who stay stuck' : 'great visuals are often what makes a seller sign with one agent over another and most realtors are leaving that edge on the table'}.
Sentence 4: Ask if they have 15 minutes to connect and book a time. Do not include any link.`,
      },
    ],
  });

  return message.content[0].text.trim();
}

// ── GHL email sender ──────────────────────────────────────────────────────────

async function sendEmailViaGHL({ contactId, email, firstName, emailBody }) {
  const GHL_API_KEY = process.env.GHL_API_KEY;
  const GHL_LOCATION_ID = process.env.GHL_LOCATION_ID;

  if (!GHL_API_KEY) {
    throw new Error('GHL_API_KEY environment variable is not set');
  }
  if (!GHL_LOCATION_ID) {
    throw new Error('GHL_LOCATION_ID environment variable is not set');
  }

  const signature = `\n\n--\nDane Saunders\nFounder & Creative Director\ndaneOmedia\nShort-Form Content for Real Estate & Capital Markets\ngrOw where ideas flOw.\nContact@daneomedia.com\n(805)-320-2723\nhttps://daneomedia.com`;

  const calendlyUrl = 'https://calendly.com/contact-daneomedia/30min';
  const calendlyButton = `<a href="${calendlyUrl}" style="display:inline-block;padding:10px 20px;background:#1c9c91;color:#fff;text-decoration:none;border-radius:4px;font-weight:bold;font-size:14px;">Book Call Today</a>`;

  const signatureHtml = `<br><br>
<p style="margin:0;font-size:14px;color:#333;line-height:1.6;">
  <strong>Dane Saunders</strong><br>
  Founder &amp; Creative Director<br>
  <strong>daneOmedia</strong><br>
  Short-Form Content for Real Estate &amp; Capital Markets<br>
  <em>grOw where ideas flOw.</em><br>
  <a href="mailto:Contact@daneomedia.com">Contact@daneomedia.com</a><br>
  (805)-320-2723<br>
  <a href="https://daneomedia.com">daneomedia.com</a>
</p>`;

  const emailBodyHtml = emailBody.replace(/\n/g, '<br>');

  const body = {
    type: 'Email',
    contactId: contactId,
    locationId: GHL_LOCATION_ID,
    emailTo: email,
    subject: `Quick question for ${firstName || 'you'}`,
    message: emailBody + `\n\nBook Call Today: ${calendlyUrl}` + signature,
    html: `<p>${emailBodyHtml}</p><br>${calendlyButton}${signatureHtml}`,
  };

  console.log('GHL request body:', JSON.stringify(body));
  console.log('GHL API key (first 8 chars):', GHL_API_KEY.substring(0, 8));

  let response;
  try {
    response = await axios.post(
      'https://services.leadconnectorhq.com/conversations/messages',
      body,
      {
        headers: {
          Authorization: `Bearer ${GHL_API_KEY}`,
          'Content-Type': 'application/json',
          Version: '2021-07-28',
        },
      }
    );
  } catch (err) {
    const status = err.response?.status;
    const data = err.response?.data;
    console.error(`GHL API error ${status}:`, JSON.stringify(data));
    throw new Error(`GHL API ${status}: ${JSON.stringify(data)}`);
  }

  return response.data;
}

// ── Start server ──────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`Webhook server listening on port ${PORT}`);
});
