require('dotenv').config();

const express = require('express');
const Anthropic = require('@anthropic-ai/sdk');
const axios = require('axios');

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

let anthropic = null;
function getAnthropicClient() {
  if (!anthropic) {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY environment variable is not set');
    }
    anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return anthropic;
}

// ── Health check ─────────────────────────────────────────────────────────────

app.get('/health', (req, res) => {
  res.send('server is running');
});

// ── Webhook endpoint ──────────────────────────────────────────────────────────

app.post('/webhook', async (req, res) => {
  try {
    const payload = req.body;

    // Extract contact fields from GHL webhook payload
    const firstName   = payload.first_name   || payload.firstName   || 'there';
    const companyName = payload.company_name  || payload.companyName || payload.company || '';
    const email       = payload.email         || payload.contactEmail || '';
    const tagsArray   = Array.isArray(payload.tags) ? payload.tags : (payload.tags ? String(payload.tags).split(',').map(t => t.trim()) : []);
    const industry    = payload.industry      || tagsArray.find(t => t)     || 'your industry';
    const contactId   = payload.contact_id    || payload.contactId   || payload.id || '';

    if (!email) {
      console.warn('Webhook received with no email address — skipping.');
      return res.status(400).json({ error: 'Missing email address in payload' });
    }

    console.log(`Processing contact: ${firstName} <${email}> — ${companyName}`);

    // ── Generate email with Claude ──────────────────────────────────────────

    const emailBody = await generateEmail({ firstName, companyName, industry });
    console.log('Email generated by Claude:\n', emailBody);

    // ── Send email via GHL API ──────────────────────────────────────────────

    await sendEmailViaGHL({ contactId, email, firstName, emailBody });
    console.log(`Email sent to ${email}`);

    res.json({ success: true, message: `Email sent to ${email}` });

  } catch (err) {
    console.error('Error processing webhook:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── Claude email generator ────────────────────────────────────────────────────

async function generateEmail({ firstName, companyName, industry }) {
  const companyContext = companyName ? `at ${companyName}` : '';
  const industryContext = industry && industry !== 'your industry'
    ? `in the ${industry} space`
    : '';

  const prompt = `Write a short cold outreach email to ${firstName}${companyContext ? ` at ${companyName}` : ''} from DaneOmedia.

DaneOmedia helps realtors get more listings with professional photo and video content.

Tone and style rules:
Write like a real person texting a colleague they kind of know already. Casual and warm. Short sentences. Simple everyday words. No corporate or agency language at all.

Formatting rules:
No dashes or hyphens anywhere. No bullet points or lists. No subject line. Just the email body.

Do not use any of these words: tighten, outbound, leverage, deliver, solutions.

Content rules:
Use ${firstName}'s name naturally once. Mention that DaneOmedia helps realtors get more listings with professional photo and video content. End with a soft question asking if they have 15 minutes this week. Do not include a sign-off or your name.

Write only the email body now.`;

  const message = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 300,
    messages: [{ role: 'user', content: prompt }],
  });

  return message.content[0].text.trim();
}

// ── GHL email sender ──────────────────────────────────────────────────────────

async function sendEmailViaGHL({ contactId, email, firstName, emailBody }) {
  const GHL_API_KEY = process.env.GHL_API_KEY;

  if (!GHL_API_KEY) {
    throw new Error('GHL_API_KEY environment variable is not set');
  }

  // GHL v2 — send email to a contact
  // Docs: https://highlevel.stoplight.io/docs/integrations/
  const response = await axios.post(
    'https://services.leadconnectorhq.com/conversations/messages',
    {
      type: 'Email',
      contactId: contactId,
      emailTo: email,
      subject: `Quick question for ${firstName || 'you'}`,
      message: emailBody,
      html: `<p>${emailBody.replace(/\n/g, '<br>')}</p>`,
    },
    {
      headers: {
        Authorization: `Bearer ${GHL_API_KEY}`,
        'Content-Type': 'application/json',
        Version: '2021-04-15',
      },
    }
  );

  return response.data;
}

// ── Start server ──────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`Webhook server listening on port ${PORT}`);
});
