require('dotenv').config();

const express = require('express');
const Anthropic = require('@anthropic-ai/sdk');
const axios = require('axios');

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

let anthropic = null;
function getAnthropicClient() {
  if (!anthropic) {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY environment variable is not set');
    }
    anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return anthropic;
}

// ── Health check ─────────────────────────────────────────────────────────────

app.get('/health', (req, res) => {
  res.send('server is running');
});

// ── Webhook endpoint ──────────────────────────────────────────────────────────

app.post('/webhook', async (req, res) => {
  try {
    const payload = req.body;

    // Extract contact fields from GHL webhook payload
    const firstName   = payload.first_name   || payload.firstName   || 'there';
    const companyName = payload.company_name  || payload.companyName || payload.company || '';
    const email       = payload.email         || payload.contactEmail || '';
    const tagsArray   = Array.isArray(payload.tags) ? payload.tags : (payload.tags ? String(payload.tags).split(',').map(t => t.trim()) : []);
    const industry    = payload.industry      || tagsArray.find(t => t)     || 'your industry';
    const contactId   = payload.contact_id    || payload.contactId   || payload.id || '';

    if (!email) {
      console.warn('Webhook received with no email address — skipping.');
      return res.status(400).json({ error: 'Missing email address in payload' });
    }

    console.log(`Processing contact: ${firstName} <${email}> — ${companyName}`);

    // ── Generate email with Claude ──────────────────────────────────────────

    const emailBody = await generateEmail({ firstName, companyName, industry });
    console.log('Email generated by Claude:\n', emailBody);

    // ── Send email via GHL API ──────────────────────────────────────────────

    await sendEmailViaGHL({ contactId, email, firstName, emailBody });
    console.log(`Email sent to ${email}`);

    res.json({ success: true, message: `Email sent to ${email}` });

  } catch (err) {
    console.error('Error processing webhook:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── Claude email generator ────────────────────────────────────────────────────

async function generateEmail({ firstName, companyName }) {
  const prompt = `You are writing a short personal message to ${firstName}, a realtor${companyName ? ` at ${companyName}` : ''}.

Write exactly 4 sentences. No more.

Here is what each sentence must do:
Sentence 1: Say hi to ${firstName} in a warm casual way, like you already know them a little.
Sentence 2: Mention that you work with realtors and that professional photos and video help them win more listings.
Sentence 3: Say something brief and genuine about why good visuals matter when a seller is choosing an agent.
Sentence 4: Ask if they have 15 minutes this week to chat.

Hard rules. Follow every single one:
Do not use any dashes or hyphens.
Do not use bullet points or lists.
Do not use these words or anything close to them: outbound, pipeline, deliverability, leverage, solutions, agency, cold, strategy, tighten, deliver.
Do not mention emails, campaigns, or marketing.
Write like a real person sending a text to someone they kind of know. Warm and casual. Short simple words.
Do not include a greeting line, subject line, sign off, or your name. Just the 4 sentences.

Write the 4 sentences now.`;

  const message = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 300,
    messages: [{ role: 'user', content: prompt }],
  });

  return message.content[0].text.trim();
}

// ── GHL email sender ──────────────────────────────────────────────────────────

async function sendEmailViaGHL({ contactId, email, firstName, emailBody }) {
  const GHL_API_KEY = process.env.GHL_API_KEY;
  const GHL_LOCATION_ID = process.env.GHL_LOCATION_ID;

  if (!GHL_API_KEY) {
    throw new Error('GHL_API_KEY environment variable is not set');
  }
  if (!GHL_LOCATION_ID) {
    throw new Error('GHL_LOCATION_ID environment variable is not set');
  }

  const body = {
    type: 'Email',
    contactId: contactId,
    locationId: GHL_LOCATION_ID,
    emailTo: email,
    subject: `Quick question for ${firstName || 'you'}`,
    message: emailBody,
    html: `<p>${emailBody.replace(/\n/g, '<br>')}</p>`,
  };

  console.log('GHL request body:', JSON.stringify(body));
  console.log('GHL API key (first 8 chars):', GHL_API_KEY.substring(0, 8));

  let response;
  try {
    response = await axios.post(
      'https://services.leadconnectorhq.com/conversations/messages',
      body,
      {
        headers: {
          Authorization: `Bearer ${GHL_API_KEY}`,
          'Content-Type': 'application/json',
          Version: '2021-04-15',
        },
      }
    );
  } catch (err) {
    const status = err.response?.status;
    const data = err.response?.data;
    console.error(`GHL API error ${status}:`, JSON.stringify(data));
    throw new Error(`GHL API ${status}: ${JSON.stringify(data)}`);
  }

  return response.data;
}

// ── Start server ──────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`Webhook server listening on port ${PORT}`);
});
